name: Java CI with Gradle

on:
  push:
    tags:
      - '*'


env:
  DEV_VERSION: 2.0.1.dev1

permissions:
  # need contents write permission to create release... careful with this because it is a broad permission
  contents: write

jobs:
  build-release-jar:
    name: build and release Kangooroo Distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up JDK 11
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Change version of build.gradle to use current tag
        run: sed -i -e "s/\${{ github.ref_name }}/$DEV_VERSION/g" build.gradle
      - name: Change version of conf.yml to use current tag
        run: sed -i -e "s/\${{ github.ref_name }}/$DEV_VERSION/g" resources/conf.yml
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 7.4.2
        run: gradle distZip

      - name: Distribute Zip as lastest stable release
        uses: softprops/action-gh-release@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') && contains(github.ref, 'stable')}}
          with:
          make_latest: true
          files: | 
            build/distributions/*.zip
            - run: gradle distZip
      - name: Distribute Zip as dev release
        uses: softprops/action-gh-release@v2

        if: ${{ startsWith(github.ref, 'refs/tags/') && contains(github.ref, 'dev')}}
        with:
          make_latest: false
          files: | 
            build/distributions/*.zip
            
