name: Java CI with Gradle

on:
  push:
    tags:
      - '*'


permissions:
  # need contents write permission to create release... careful with this because it is a broad permission
  contents: write

jobs:
  build-release-jar:
    name: build and release Kangooroo Distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up JDK 11
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 7.0.2
      - run: gradle distZip
      - name: Check if tmp folder is empty
        run: ls -l
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: | 
            build/distribution/*.zip
