name: Java CI with Gradle

on:
  push:
    tags:
      - '*'


permissions:
  # need contents write permission to create release... careful with this because it is a broad permission
  contents: write

jobs:
  build-release-jar:
    name: build and release Kangooroo ShadowJar
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up JDK 11
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 7.0.2
      - run: gradle shadowJar
      - run: gradle distZip
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: | 
            build/libs/KangoorooStandalone.jar
            build/distribution/*
